puts "Some students in my cohort at Makers Academy"
puts "---------------"
puts "Andy Newman"
puts "Keiran Goodacre"
puts "Bebbs"
puts "Marcin Wal"
puts "Emily Sas"
puts "Marcus de Wilde"
puts "Matteo Manzo"